### ISSUE TITLE
different number of clusters by year ivreg_ss

### ISSUE THREAD

**Issue by federicoscabbia** [kolesarm/ShiftShareSEMatlab#1]
Hi,
I was wondering how could I approach the fact that my cluster number varies between time periods.
I have data divided in 3 decades and three corresponding cluster vectors of size (1139x14, 1132x14 and 1131x14),however  the matlab function ivreg_ss requests one cluster vector. Is there a workaround on the issue?

Thanks a lot!
Federico

**Comment by kolesarm** [comment]
It's a good question. I am assuming that the clusters vectors of different length because some industries are not observed in all periods? Our recommendation in a panel data context is to allow for correlations in the shocks across time, so that industry shocks for different time periods belong to the same cluster. This way there should just be one cluster vector. See Section V.B in the paper for more detail.
