### ISSUE TITLE
small number of shifters

### ISSUE THREAD

**Issue by federicoscabbia** [kolesarm/ShiftShareSEMatlab#2]
Good morning, I'm dealing with a panel dataset with three periods and 15 shifters. Do you have any suggestions to deal with the small number of clusters, like clustering at shifter-period level vs shifter level to increase the number of the clusters? Do you think your method is still viable for such a small number of clusters?
Thanks a lot

**Comment by kolesarm** [comment]
The problem is analogous to computing clustered standard errors with a small number of clusters. You're right, one solution is to assume that the shocks to a given sector are not correlated across periods. Then it is sufficient to "cluster" at a sector-period level (you'd then effectively have 15*3=45 different sectors, and you just implement our correction without any clustering). Whether you do this, or you cluster at the sector level (you'd effectively have 15 independent sectors). 

With a small number of sectors, the AKM0 method is more reliable, so we recommend using it over the AKM method.
